name: "pull-request"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

env:
  IMAGE_NAME: ansible-goss

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint
        run: make lint
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image
        run: make build
      - name: Save image
        run: docker save -o /tmp/${{ env.IMAGE_NAME }}.tar ${{ env.IMAGE_NAME }}:latest
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.IMAGE_NAME }}
          path: /tmp/${{ env.IMAGE_NAME }}.tar
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    needs: [lint, build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetch artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.IMAGE_NAME }}
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/${{ env.IMAGE_NAME }}.tar
      - name: Run test
        run: make test-jnit
      - name: Report test
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'goss-validate.xml'
          require_tests: true
          fail_on_failure: true
